#!/usr/bin/env sh
gpg --keyserver pgpkeys.mit.edu --recv-key  8B48AD6246925553
gpg -a --export 8B48AD6246925553 | sudo apt-key add -
curl https://ftp-master.debian.org/keys/archive-key-8.asc | sudo apt-key add -
curl https://ftp-master.debian.org/keys/archive-key-8-security.asc | sudo apt-key add -
echo "deb http://ftp.debian.org/debian jessie-backports main" | sudo tee /etc/apt/sources.list.d/backports.list
sudo apt update
