#!/usr/bin/env sh
set -ex
#. /etc/os-release
sudo apt install -y lsb-release apt-transport-https
codename=`lsb_release -cs`

# openvpn
#curl -sSL https://swupdate.openvpn.net/repos/repo-public.gpg | sudo apt-key add -
#echo "deb http://build.openvpn.net/debian/openvpn/stable $codename main" | sudo tee /etc/apt/sources.list.d/openvpn.list

# docker-ce
curl -sSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
echo "deb [arch=amd64,armhf] https://download.docker.com/linux/ubuntu $codename stable" | sudo tee /etc/apt/sources.list.d/docker.list

# nodejs
curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
