#!/usr/bin/env bash
# Usage:
#   ./install-remote ip hostname
set -x
ip=$1
hostname=$2

if [[ -f ~/.local/etc/ddns ]]; then
  . ~/.local/etc/ddns
  data='{"type":"A","name":"${name}","content":"${ip}","ttl":120,"proxied":false}'
  data=${data//$\{ip\}/$ip}
  data=${data//$\{name\}/$hostname}

  curl -sS -X POST "https://api.cloudflare.com/client/v4/zones/${zone_id}/dns_records" \
       -H "X-Auth-Email: $auth_email" \
       -H "X-Auth-Key: $auth_key" \
       -H "Content-Type: application/json" \
       --data $data
  echo
fi

ssh-copy-id root@$ip
ssh root@$ip "
adduser --disabled-password --gecos '' $USER
echo \"$USER ALL=(ALL) NOPASSWD:ALL\" >/etc/sudoers.d/$USER
cp -r .ssh /home/$USER
chown -R $USER:$USER /home/$USER/.ssh
"

zoneinfo=`readlink /etc/localtime`
ssh $USER@$ip "
echo 127.0.0.1 $hostname | sudo tee -a /etc/hosts
echo $hostname | sudo tee /etc/hostname
sudo hostname $hostname
sudo ln -sf $zoneinfo /etc/localtime
sudo apt-get update
sudo apt-get install -y git tmux sshguard cron gnupg2
git clone https://github.com/crzidea/confbook.git ~/.confbook
~/.confbook/install
"
