#!/usr/bin/env bash
# Usage:
#   ./install-remote ip hostname
set -x
ip=$1
hostname=$2

if [[ -f ~/.local/etc/ddns ]]; then
  . ~/.local/etc/ddns
  data='{"type":"A","name":"${name}","content":"${ip}","ttl":120,"proxied":false}'
  data=${data//$\{ip\}/$ip}
  data=${data//$\{name\}/$hostname}

  curl -sS -X POST "https://api.cloudflare.com/client/v4/zones/${zone_id}/dns_records" \
       -H "X-Auth-Email: $auth_email" \
       -H "X-Auth-Key: $auth_key" \
       -H "Content-Type: application/json" \
       --data $data
  echo
fi

ssh-copy-id root@$ip
ssh root@$ip "
apt-get update
apt-get install -y git tmux sshguard cron gnupg2 dnsutils sudo vim curl bash-completion
adduser --disabled-password --gecos '' $USER
usermod -aG sudo $USER
echo \"$USER ALL=(ALL) NOPASSWD:ALL\" >/etc/sudoers.d/$USER
cp -r .ssh /home/$USER
chown -R $USER:$USER /home/$USER/.ssh
"

zoneinfo=`readlink /etc/localtime`

ssh $USER@$ip "rm -rf ~/git-bare/"

function copy_git_repo() {
  repo=$1
  ssh $USER@$ip "
mkdir -p ~/git-bare/$repo
cd ~/git-bare/$repo
git init --bare
"
  cd $repo
  git_remote_name=host-$hostname
  git remote remove $git_remote_name
  git remote add $git_remote_name ssh://$USER@$ip/~/git-bare/$repo
  git push --all $git_remote_name
  ssh $USER@$ip "
rm -rf $repo
git clone ~/git-bare/$repo $repo
rm -rf ~/git-bare/$repo
"
}

copy_git_repo "~/.confbook"
copy_git_repo "~/.local-bin"
#mkdir -p "~/.vim/bundle"
copy_git_repo "~/.vim/bundle/Vundle.vim"

ssh $USER@$ip "
echo | sudo tee -a /etc/hosts
echo 127.0.0.1 $hostname | sudo tee -a /etc/hosts
echo ::1 $hostname | sudo tee -a /etc/hosts
echo $hostname | sudo tee /etc/hostname
sudo hostname $hostname
sudo ln -sf $zoneinfo /etc/localtime
#git clone https://github.com/crzidea/confbook.git ~/.confbook
NO_INTERNET=1 ~/.confbook/install
~/.confbook/apt/docker
#~/.confbook/apt/cloudflare-warp
rm -r ~/git-bare
sudo passwd --lock root
"
