#!/usr/bin/env sh
#set -ex
#. ./vars

# https://developers.cloudflare.com/warp-client/get-started/linux/
# Add cloudflare gpg key
curl -fsSL https://pkg.cloudflareclient.com/pubkey.gpg | sudo gpg --yes --dearmor --output /usr/share/keyrings/cloudflare-warp-archive-keyring.gpg

# Add this repo to your apt repositories
echo "deb [arch=amd64 signed-by=/usr/share/keyrings/cloudflare-warp-archive-keyring.gpg] https://pkg.cloudflareclient.com/ $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/cloudflare-client.list

# Install
sudo apt-get update && sudo apt-get install cloudflare-warp -y

sudo systemctl disable warp-svc.service
mkdir -p ~/.local/share/warp
echo yes > ~/.local/share/warp/accepted-tos.txt

# Add login IP to excluded route list
echo $SSH_CONNECTION | sed 's/ .*//' | xargs warp-cli --accept-tos add-excluded-route
warp-cli --accept-tos add-excluded-route 0.0.0.0/0
warp-cli --accept-tos add-excluded-route ::/0
warp-cli --accept-tos get-excluded-routes
warp-cli --accept-tos dns fallback add engage.cloudflareclient.com
warp-cli --accept-tos mode tunnel_only
warp-cli --accept-tos registration new
#warp-cli --accept-tos connect
#curl --interface CloudflareWARP https://api.ipify.org; echo
