#!/usr/bin/env sh
set -ex
. ./vars

# nodejs
#curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
echo "deb $mirrors/http/deb.nodesource.com/node_8.x $codename main" | sudo tee /etc/apt/sources.list.d/nodesource.list
echo "deb-src $mirrors/http/deb.nodesource.com/node_8.x $codename main" | sudo tee -a /etc/apt/sources.list.d/nodesource.list
