#!/usr/bin/env bash
sudo apt install -y apt-transport-https
. /etc/os-release
if [ -z $VERSION_CODENAME ]; then
  sudo apt install -y lsb-release
  codename=`lsb_release -cs`
else
  codename=$VERSION_CODENAME
fi
mirrors="https://mirrors.crzidea.com"
